# Generated by Django 5.0 on 2025-11-20 01:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TranchesDefinition',
            fields=[
                ('deal_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('dated_date', models.DateField(blank=True, null=True)),
                ('first_pay_date', models.DateField(blank=True, null=True)),
                ('delay', models.IntegerField(blank=True, help_text='Payment delay in days', null=True)),
                ('pay_freq', models.CharField(blank=True, help_text='Payment frequency', max_length=50, null=True)),
                ('interest_day_count', models.CharField(blank=True, max_length=50, null=True)),
                ('currency', models.CharField(default='USD', max_length=10)),
            ],
            options={
                'db_table': 'tranches_definition',
            },
        ),
        migrations.CreateModel(
            name='Prospectus',
            fields=[
                ('prospectus_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prospectus_name', models.CharField(max_length=255)),
                ('prospectus_file', models.FileField(upload_to='prospectus/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('parsed_pages', models.JSONField(blank=True, default=list)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prospectuses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'prospectus',
                'ordering': ['-upload_date'],
            },
        ),
        migrations.CreateModel(
            name='TrancheDeclaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('principal_type', models.CharField(blank=True, max_length=50, null=True)),
                ('coupon_type', models.CharField(blank=True, max_length=50, null=True)),
                ('coupon_rate', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('delay', models.IntegerField(blank=True, help_text='Tranche-specific delay', null=True)),
                ('group_name', models.CharField(blank=True, max_length=100, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('deal_id', models.ForeignKey(db_column='deal_id', on_delete=django.db.models.deletion.CASCADE, related_name='tranches', to='core.tranchesdefinition')),
            ],
            options={
                'db_table': 'tranche_declaration',
            },
        ),
        migrations.CreateModel(
            name='DealScript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script_content', models.TextField()),
                ('generated_date', models.DateTimeField(auto_now_add=True)),
                ('collateral_groups', models.JSONField(blank=True, default=list)),
                ('deal_tree', models.JSONField(blank=True, default=dict)),
                ('prospectus_id', models.ForeignKey(db_column='prospectus_id', on_delete=django.db.models.deletion.CASCADE, related_name='deal_scripts', to='core.prospectus')),
                ('deal_id', models.ForeignKey(db_column='deal_id', on_delete=django.db.models.deletion.CASCADE, related_name='scripts', to='core.tranchesdefinition')),
            ],
            options={
                'db_table': 'deal_script',
                'ordering': ['-generated_date'],
            },
        ),
        migrations.CreateModel(
            name='ProspectusSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('deal_summary', 'Deal Summary'), ('deal_structure', 'Deal Structure'), ('tranche_list', 'Tranche List'), ('tranche_details', 'Tranche Details'), ('collateral_detail', 'Collateral Detail'), ('payment_priority', 'Payment Priority'), ('interest_distribution', 'Interest Distribution'), ('principal_distribution', 'Principal Distribution'), ('default_loss', 'Default Loss Distribution'), ('prepayment_penalty', 'Prepayment Penalty'), ('risk_factors', 'Risk Factors'), ('other', 'Other')], max_length=50)),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField()),
                ('page_numbers', models.JSONField(default=list)),
                ('level', models.IntegerField(default=0)),
                ('order', models.IntegerField(default=0)),
                ('structured_data', models.JSONField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subsections', to='core.prospectussection')),
                ('prospectus_id', models.ForeignKey(db_column='prospectus_id', on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='core.prospectus')),
            ],
            options={
                'db_table': 'prospectus_section',
                'ordering': ['prospectus_id', 'order'],
                'indexes': [models.Index(fields=['prospectus_id', 'section_type'], name='prospectus__prospec_4cfc87_idx'), models.Index(fields=['parent'], name='prospectus__parent__7a2247_idx')],
            },
        ),
    ]
