# Generated by Django 5.0 on 2025-11-01 02:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='New Conversation', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'conversation',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Prospectus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='prospectus/')),
                ('filename', models.CharField(max_length=255)),
                ('deal_name', models.CharField(blank=True, max_length=255, null=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('file_size', models.BigIntegerField()),
                ('processing_status', models.CharField(choices=[('uploaded', 'Uploaded'), ('parsing', 'Parsing'), ('parsed', 'Parsed'), ('failed', 'Failed')], default='uploaded', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'prospectus',
                'ordering': ['-upload_date'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=20)),
                ('content', models.TextField()),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('script_generation', 'Script Generation'), ('query_analysis', 'Query Analysis'), ('error', 'Error')], default='text', max_length=30)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.conversation')),
            ],
            options={
                'db_table': 'message',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='conversation',
            name='prospectus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='core.prospectus'),
        ),
        migrations.CreateModel(
            name='SectionMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section_type', models.CharField(choices=[('deal_summary', 'Deal Summary'), ('deal_structure', 'Deal Structure'), ('tranche_list', 'Tranche List'), ('tranche_details', 'Tranche Details'), ('collateral_detail', 'Collateral Detail'), ('payment_priority', 'Payment Priority'), ('interest_distribution', 'Interest Distribution'), ('principal_distribution', 'Principal Distribution'), ('default_loss', 'Default Loss Distribution'), ('prepayment_penalty', 'Prepayment Penalty'), ('risk_factors', 'Risk Factors'), ('other', 'Other')], max_length=50)),
                ('section_title', models.CharField(max_length=500)),
                ('content', models.TextField()),
                ('page_numbers', models.JSONField(default=list)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prospectus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='core.prospectus')),
            ],
            options={
                'db_table': 'section_mapping',
                'ordering': ['prospectus', 'section_type'],
            },
        ),
        migrations.CreateModel(
            name='TrancheScript',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('script_content', models.TextField()),
                ('version', models.IntegerField(default=1)),
                ('generation_status', models.CharField(choices=[('generating', 'Generating'), ('completed', 'Completed'), ('failed', 'Failed'), ('validating', 'Validating')], default='generating', max_length=20)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_scripts', to='core.message')),
                ('prospectus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scripts', to='core.prospectus')),
            ],
            options={
                'db_table': 'tranche_script',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'created_at'], name='message_convers_5aa82f_idx'),
        ),
        migrations.AddIndex(
            model_name='sectionmapping',
            index=models.Index(fields=['prospectus', 'section_type'], name='section_map_prospec_26f12f_idx'),
        ),
        migrations.AddIndex(
            model_name='tranchescript',
            index=models.Index(fields=['prospectus', '-version'], name='tranche_scr_prospec_f64e41_idx'),
        ),
    ]
