# Generated by Django 5.0 on 2025-12-20 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospectus',
            name='index_page_numbers',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='prospectus',
            name='parse_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('parsing_index', 'Parsing Index'), ('parsing_sections', 'Parsing Sections'), ('classifying', 'Classifying'), ('storing', 'Storing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', help_text='Current parsing status of the prospectus', max_length=20),
        ),
        migrations.AddField(
            model_name='prospectus',
            name='parsed_file',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='prospectus',
            name='parsed_index',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
