# Generated by Django 5.0 on 2026-01-06 01:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_prospectus_index_page_numbers_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='prospectus',
            constraint=models.UniqueConstraint(fields=('prospectus_name', 'created_by'), name='unique_prospectus_per_user'),
        ),
    ]
