# Generated by Django 5.0 on 2026-01-06 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_unique_prospectus_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospectus',
            name='parse_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('parsing_index', 'Parsing Index'), ('parsing_sections', 'Parsing Sections'), ('classifying', 'Classifying'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', help_text='Current parsing status of the prospectus', max_length=20),
        ),
    ]
