# Generated by Django 5.0 on 2026-01-18 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_prospectus_parse_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prospectussection',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='prospectussection',
            name='prospectus_id',
        ),
        migrations.RemoveField(
            model_name='tranchedeclaration',
            name='deal_id',
        ),
        migrations.AlterField(
            model_name='prospectus',
            name='parse_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('parsing_index', 'Parsing Index'), ('parsing_sections', 'Parsing Sections'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', help_text='Current parsing status of the prospectus', max_length=20),
        ),
        migrations.DeleteModel(
            name='DealScript',
        ),
        migrations.DeleteModel(
            name='ProspectusSection',
        ),
        migrations.DeleteModel(
            name='TrancheDeclaration',
        ),
        migrations.DeleteModel(
            name='TranchesDefinition',
        ),
    ]
