# Generated by Django 5.0 on 2026-01-19 02:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_prospectussection_parent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationThread',
            fields=[
                ('thread_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prospectus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_threads', to='core.prospectus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_threads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'conversation_thread',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('message_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System'), ('tool', 'Tool')], max_length=20)),
                ('content', models.TextField()),
                ('tool_calls', models.JSONField(blank=True, default=list, null=True)),
                ('tool_call_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.conversationthread')),
            ],
            options={
                'db_table': 'chat_message',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentCheckpoint',
            fields=[
                ('checkpoint_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('checkpoint_ns', models.CharField(blank=True, default='', max_length=255)),
                ('checkpoint', models.JSONField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('parent_checkpoint_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='core.conversationthread')),
            ],
            options={
                'db_table': 'agent_checkpoint',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='conversationthread',
            constraint=models.UniqueConstraint(fields=('user', 'prospectus'), name='unique_thread_per_user_prospectus'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['thread', 'created_at'], name='chat_messag_thread__9895ae_idx'),
        ),
        migrations.AddIndex(
            model_name='agentcheckpoint',
            index=models.Index(fields=['thread', 'checkpoint_ns', 'created_at'], name='agent_check_thread__4df2dd_idx'),
        ),
    ]
