# Generated by Django 5.0 on 2026-04-24 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_prospectus_chunk_with_pgvector'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='prospectuschunk',
            new_name='prospectus__prospec_5b0728_idx',
            old_name='prospectus_chunk_prosp_idx',
        ),
        migrations.RenameIndex(
            model_name='prospectuschunk',
            new_name='prospectus__prospec_ca0538_idx',
            old_name='prospectus_chunk_created_idx',
        ),
        migrations.AlterField(
            model_name='prospectus',
            name='parse_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('parsing_index', 'Parsing Index'), ('parsing_sections', 'Parsing Sections'), ('creating_chunks', 'Creating Chunks'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', help_text='Current parsing status of the prospectus', max_length=20),
        ),
    ]
